name: Test

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Test .github folder
        uses: ./.github/actions/secrets

      - name: Test non github folder
        uses: ./test-action